-- Run this file in the Supabase SQL Editor.
-- User ownership references Supabase Auth directly; no public users table is needed.

create table if not exists public.luciussynth_musicdocuments (
  id bigint generated by default as identity primary key,
  url text not null,
  name text not null,
  content text not null,
  tempo integer not null,
  meter text not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  created bigint not null,
  edited bigint not null
);

create index if not exists luciussynth_musicdocuments_user_id_idx
  on public.luciussynth_musicdocuments (user_id);

create index if not exists luciussynth_musicdocuments_edited_idx
  on public.luciussynth_musicdocuments (edited desc);

create table if not exists public.luciussynth_posts (
  id bigint generated by default as identity primary key,
  url text not null,
  name text not null,
  content text not null,
  user_id uuid references auth.users (id) on delete set null,
  created bigint not null,
  edited bigint not null
);

create index if not exists luciussynth_posts_user_id_idx
  on public.luciussynth_posts (user_id);

create index if not exists luciussynth_posts_edited_idx
  on public.luciussynth_posts (edited desc);

-- All database access currently goes through Next.js server routes using the
-- service-role key, which is kept server-side and bypasses RLS. Enable RLS so
-- accidental anon-key access is denied by default.
alter table public.luciussynth_musicdocuments enable row level security;
alter table public.luciussynth_posts enable row level security;
